# Generated by Django 5.1.1 on 2024-09-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialalimentos',
            old_name='fecha',
            new_name='date_join',
        ),
        migrations.RenameField(
            model_name='minuta',
            old_name='state',
            new_name='state_minuta',
        ),
        migrations.RenameField(
            model_name='minuta',
            old_name='tipe_food',
            new_name='type_food',
        ),
    ]
