# Generated by Django 5.1.1 on 2024-09-19 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_rename_fecha_historialalimentos_date_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensa',
            name='alimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apirest.alimento'),
        ),
    ]
