# Generated by Django 5.1.1 on 2024-09-19 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_alter_dispensa_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensa',
            name='alimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apirest.alimento'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dispensa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apirest.dispensa'),
        ),
    ]
