# Generated by Django 5.1.1 on 2024-09-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_alter_dispensa_alimento_alter_users_dispensa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensa',
            name='alimento',
        ),
        migrations.CreateModel(
            name='DispensaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.alimento')),
                ('dispensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.dispensa')),
            ],
            options={
                'db_table': 'apirest_dispensa_alimentos',
                'unique_together': {('dispensa', 'alimento')},
            },
        ),
        migrations.AddField(
            model_name='dispensa',
            name='alimentos',
            field=models.ManyToManyField(blank=True, through='apirest.DispensaAlimento', to='apirest.alimento'),
        ),
    ]
