# Generated by Django 5.1.1 on 2024-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_remove_dispensa_alimento_dispensaalimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='load_alimento',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
