# Generated by Django 5.1.1 on 2024-10-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0006_alter_alimento_load_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='load_alimento',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
