# Generated by Django 5.1.1 on 2024-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0008_alter_alimento_load_alimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialalimentos',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='historialalimentos',
            name='dispensa',
        ),
        migrations.RemoveField(
            model_name='historialalimentos',
            name='user',
        ),
        migrations.AddField(
            model_name='historialalimentos',
            name='alimento_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialalimentos',
            name='dispensa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialalimentos',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
