# Generated by Django 5.1.1 on 2024-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0010_remove_minuta_state_minuta_remove_minuta_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular'), ('student', 'Estudiante'), ('worker', 'Trabajador'), ('homemaker', 'Dueño de casa')], max_length=50),
        ),
    ]
