# Generated by Django 5.1.1 on 2024-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0011_alter_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaminuta',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaminuta',
            name='nombre_lista_minuta',
            field=models.CharField(default='Default Name', max_length=50),
            preserve_default=False,
        ),
    ]
