# Generated by Django 5.1.1 on 2024-10-17 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0014_alter_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=50),
            preserve_default=False,
        ),
    ]
