# Generated by Django 5.1.1 on 2024-10-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0015_users_date_join_users_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaminuta',
            name='state_minuta',
            field=models.CharField(max_length=50),
        ),
    ]
