# Generated by Django 5.1.1 on 2024-10-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0016_alter_listaminuta_state_minuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='infominuta',
            name='alimentos_usados_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
