# Generated by Django 5.1.1 on 2024-10-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0017_infominuta_alimentos_usados_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='uso_alimento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
