# Generated by Django 5.1.1 on 2024-11-03 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0019_sugerencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutaIngrediente',
            fields=[
                ('id_minuta_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ingrediente', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=50)),
                ('id_minuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='apirest.minuta')),
            ],
        ),
    ]
