# Generated by Django 5.1.1 on 2024-11-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0020_minutaingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialalimentos',
            name='alimento_id',
        ),
        migrations.RemoveField(
            model_name='historialalimentos',
            name='date_join',
        ),
        migrations.RemoveField(
            model_name='historialalimentos',
            name='dispensa_id',
        ),
    ]
