# Generated by Django 5.1.1 on 2024-11-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0021_remove_historialalimentos_alimento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialalimentos',
            name='uso_alimento',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
