# Generated by Django 5.1.1 on 2024-11-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0022_historialalimentos_uso_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialalimentos',
            name='load_alimento',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
