# Generated by Django 5.1.1 on 2024-11-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0023_alter_historialalimentos_load_alimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='infominuta',
            name='tipo_alimento',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
