# Generated by Django 5.1.1 on 2024-11-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0025_objetivo_progresoobjetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='tipo_objetivo',
            field=models.CharField(choices=[('minutas completas', 'Minutas completas'), ('lista de minutas completas', 'Lista de minutas completas'), ('vegetales usados', 'Vegetales usados'), ('frutas usadas', 'Frutas usadas'), ('carbohidratos usados', 'Carbohidratos usados')], max_length=100),
        ),
    ]
