# Generated by Django 5.1.1 on 2024-11-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0028_objetivo_state_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutaingrediente',
            name='tipo_medida',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
