# Generated by Django 5.1.1 on 2024-11-16 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0029_minutaingrediente_tipo_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alimentos_ingresados', models.PositiveIntegerField(default=0)),
                ('total_alimentos_eliminados', models.PositiveIntegerField(default=0)),
                ('total_minutas_creadas', models.PositiveIntegerField(default=0)),
                ('total_minutas_completadas', models.PositiveIntegerField(default=0)),
                ('total_planes_creados', models.PositiveIntegerField(default=0)),
                ('total_planes_completados', models.PositiveIntegerField(default=0)),
                ('porcentaje_alimentos_aprovechados', models.FloatField(default=0.0)),
                ('promedio_duracion_alimentos', models.FloatField(default=0.0)),
                ('reduccion_desperdicio', models.FloatField(default=0.0)),
                ('proporcion_planes_completados', models.FloatField(default=0.0)),
                ('impacto_alimentos_minutas', models.FloatField(default=0.0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='apirest.users')),
            ],
        ),
    ]
