# Generated by Django 5.1.1 on 2024-11-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0033_alter_historialalimentos_dias_en_despensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desperdicio',
            fields=[
                ('id_desperdicio', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.FloatField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
