# Generated by Django 5.1.1 on 2024-11-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0035_infominuta_contado_en_estadisticas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticasusuario',
            name='impacto_alimentos_minutas',
        ),
    ]
